/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "eap.v:1" *)
module eap(clock, reset, io_pc, io_out);
  (* src = "eap.v:2" *)
  input clock;
  (* src = "eap.v:5" *)
  output io_out;
  (* src = "eap.v:4" *)
  input [26:0] io_pc;
  (* src = "eap.v:3" *)
  input reset;
  assign io_out = 1'b0;
endmodule
